// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfgiokVRWF0o0gBY0eFNvVb-UXmP1ma8s',
    appId: '1:459766644218:web:c4fa9c1e6dd232190df843',
    messagingSenderId: '459766644218',
    projectId: 'shopping-app-vendor',
    authDomain: 'shopping-app-vendor.firebaseapp.com',
    storageBucket: 'shopping-app-vendor.firebasestorage.app',
    measurementId: 'G-S2R281BP5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr_mE5ZoSOD5sFU3xjW_gODpshY_rm4GA',
    appId: '1:459766644218:android:d08b5cebc1460f750df843',
    messagingSenderId: '459766644218',
    projectId: 'shopping-app-vendor',
    storageBucket: 'shopping-app-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdEw8Y5A3r9x45vpvBoQP2t-QqqYMVano',
    appId: '1:459766644218:ios:fa214adc383a27420df843',
    messagingSenderId: '459766644218',
    projectId: 'shopping-app-vendor',
    storageBucket: 'shopping-app-vendor.firebasestorage.app',
    iosBundleId: 'com.example.appVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdEw8Y5A3r9x45vpvBoQP2t-QqqYMVano',
    appId: '1:459766644218:ios:fa214adc383a27420df843',
    messagingSenderId: '459766644218',
    projectId: 'shopping-app-vendor',
    storageBucket: 'shopping-app-vendor.firebasestorage.app',
    iosBundleId: 'com.example.appVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfgiokVRWF0o0gBY0eFNvVb-UXmP1ma8s',
    appId: '1:459766644218:web:c72c5cef1bac313e0df843',
    messagingSenderId: '459766644218',
    projectId: 'shopping-app-vendor',
    authDomain: 'shopping-app-vendor.firebaseapp.com',
    storageBucket: 'shopping-app-vendor.firebasestorage.app',
    measurementId: 'G-SZRKD3XZDB',
  );
}
